function [scenario] = PhasedSetup_CAMWAR(scenario_in)
%PHASEDSETUP_CAMWAR Sets up Phased Array Toolbox system objects for CAMWAR
%   Takes scenario.wave and scenario.traj as input and outputs
%   scenario.phased struct containing system objects for Phased Array
%   Toolbox simulation.

%% Unpack Variables

scenario = scenario_in;
environment = scenario.environment;
simsetup = scenario.simsetup;
radarsetup = scenario.radarsetup;
flags = scenario.flags;


%% Set up constants

c = physconst('LightSpeed');
lambda = c/radarsetup.f_c;


%% Perform Recalculations

% Ensure integer number of samples per chirp
radarsetup.f_s = floor(radarsetup.t_ch*radarsetup.f_s)/radarsetup.t_ch;

% Calculate number of samples per chirp
radarsetup.n_s = radarsetup.f_s*radarsetup.t_ch;

%% Signal Setup

% Transmit waveform
sim.waveform = phased.FMCWWaveform( ...
    ...
    'SampleRate',               radarsetup.f_s, ...
    'SweepTime',                radarsetup.t_ch, ...
    'SweepBandwidth',           radarsetup.bw, ...
    'SweepDirection',           'Up', ...
    'SweepInterval',            'Positive', ...
    'OutputFormat',             'Sweeps', ...
    'NumSweeps',                simsetup.sim_rate);

%% Motion Platform Setup

% Set up transceiver platform
sim.radar_plat = phased.Platform( ...
    ...
    'MotionModel',              'Velocity', ...
    'InitialPosition',          simsetup.radar_pos, ...
    'Velocity',                 simsetup.radar_vel);

%% Target Setup

% Set up target to take RCS value at object call
sim.target = phased.RadarTarget( ...
    'EnablePolarization',       false, ...
    'MeanRCSSource',            'Input Port', ...
    'Model',                    'Swerling1', ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'PropagationSpeed',         c);

% Set up target platform with dummy position and velocity
sim.target_plat = phased.Platform( ...
    ...
    'MotionModel',              'Velocity', ...
    'InitialPosition',          [1000; 0; 0], ...
    'Velocity',                 [0; 0; 0]);

%% Channel Setup

% Set up channel loss model
sim.channel = phased.LOSChannel( ...
    'PropagationSpeed',         c, ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'SpecifyAtmosphere',        environment.channel_loss_on, ...
    'TwoWayPropagation',        true, ...
    'SampleRate',               radarsetup.f_s, ...
    'LiquidWaterDensity',       environment.fog_density);

%% Antenna Setup

% Set up axes for pattern computation
az_axis = -180:0.1:180;
el_axis = -90:0.1:90;
phase_pattern = zeros(length(el_axis), length(az_axis));

% Create Tx vertical array pattern
sim.tx_pattern = pow2db(SincAntennaPattern( ...
    az_axis, ...            % Input axes
    el_axis, ...        
    0, ...                  % Input beam tilt
    0, ...              
    radarsetup.tx_az_bw, ...  % Input beamwidths
    radarsetup.tx_el_bw, ...
    radarsetup.tx_az_pow, ... % Input sidelobe exponents
    radarsetup.tx_el_pow, ... 
    radarsetup.tx_gain));     % Input gain

% Create Tx antenna element object
sim.tx_antenna = phased.CustomAntennaElement( ...
    'AzimuthAngles',            az_axis, ...
    'ElevationAngles',          el_axis, ...
    'MagnitudePattern',         sim.tx_pattern, ...
    'PhasePattern',             phase_pattern);

% Create vertical Tx subarray
sim.tx_subarray = phased.ULA( ...
    'Element',                  sim.tx_antenna, ...
    'NumElements',              radarsetup.n_tx_ant, ...
    'ArrayAxis',                'z', ...
    'ElementSpacing',           lambda/2);

% Create horizontal Tx array
sim.tx_array = phased.ReplicatedSubarray( ...
    'Subarray',                 sim.tx_subarray, ...
    'Layout',                   'Rectangular', ...
    'GridSize',                 [1, radarsetup.n_tx_sub], ...
    'GridSpacing',              radarsetup.n_rx_ant*lambda/2, ...
    'SubarraySteering',         'Custom');


% Create Rx vertical array pattern
sim.rx_pattern = pow2db(SincAntennaPattern( ...
    az_axis, ...            % Input axes
    el_axis, ...        
    0, ...                  % Input beam tilt
    radarsetup.rx_el_tilt, ...              
    radarsetup.rx_az_bw, ...  % Input beamwidths
    radarsetup.rx_el_bw, ...
    radarsetup.rx_az_pow, ... % Input sidelobe exponents
    radarsetup.rx_el_pow, ... 
    radarsetup.rx_gain));     % Input gain

% Create Rx antenna element
sim.rx_antenna = phased.CustomAntennaElement( ...
    'AzimuthAngles',            az_axis, ...
    'ElevationAngles',          el_axis, ...
    'MagnitudePattern',         sim.rx_pattern, ...
    'PhasePattern',             phase_pattern);

% Create Rx horizontal array pattern
sim.rx_array = phased.ULA( ...
    'Element',                  sim.rx_antenna, ...
    'NumElements',              radarsetup.n_rx_ant, ...
    'ArrayAxis',                'y', ...
    'ElementSpacing',           lambda/2);

%% Transceiver Setup

% Set up transmitter parameters
sim.transmitter = phased.Transmitter( ...
    'PeakPower',                radarsetup.tx_pow, ...
    'Gain',                     pow2db(radarsetup.tx_gain), ...
    'LossFactor',               radarsetup.rf_sys_loss, ...
    'InUseOutputPort',          false);
    
% Set up radiation interface
sim.radiator = phased.Radiator( ...
    'Sensor',                   sim.tx_array, ...
    'PropagationSpeed',         c, ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'CombineRadiatedSignals',   true);

% Set up receiver parameters
sim.receiver = phased.ReceiverPreamp( ...
    'Gain',                     pow2db(2),  ...
    'NoiseFigure',              radarsetup.rx_nf, ...
    'SampleRate',               radarsetup.f_s);
    

% Set up receiver radiation interface
sim.collector = phased.Collector( ...
    'Sensor',                   sim.rx_array, ...
    'PropagationSpeed',         c, ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'Wavefront',                'Plane');


%% Detection Setup

% Set up CFAR detector
sim.CFAR = phased.CFARDetector2D( ...
    'Method',                   'CA', ...
    'ProbabilityFalseAlarm',    radarsetup.CFAR_Pfa, ...
    'GuardBandSize',            radarsetup.num_guard, ...
    'TrainingBandSize',         radarsetup.num_train);


%% Re-pack Variables

scenario.sim = sim;
scenario.simsetup = simsetup;
scenario.radarsetup = radarsetup;
scenario.flags = flags;
scenario.environment = environment;

end